// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CarrotCake.CMS.Plugins.PhotoGallery.Data;

#nullable disable

namespace CarrotCake.CMS.Plugins.PhotoGallery.Data.Migrations {
	[DbContext(typeof(GalleryContext))]
	[Migration("20230625212349_InitialGallery")]
	partial class InitialGallery {
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.5")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("CarrotCake.CMS.Plugins.PhotoGallery.Data.Gallery", b => {
				b.Property<Guid>("GalleryId")
					.ValueGeneratedOnAdd()
					.HasColumnType("uniqueidentifier")
					.HasColumnName("GalleryID")
					.HasDefaultValueSql("(newid())");

				b.Property<string>("GalleryTitle")
					.HasMaxLength(255)
					.IsUnicode(false)
					.HasColumnType("varchar(255)");

				b.Property<Guid?>("SiteId")
					.HasColumnType("uniqueidentifier")
					.HasColumnName("SiteID");

				b.HasKey("GalleryId")
					.HasName("tblGallery_PK");

				b.ToTable("tblGallery", (string)null);
			});

			modelBuilder.Entity("CarrotCake.CMS.Plugins.PhotoGallery.Data.GalleryImage", b => {
				b.Property<Guid>("GalleryImageId")
					.ValueGeneratedOnAdd()
					.HasColumnType("uniqueidentifier")
					.HasColumnName("GalleryImageID")
					.HasDefaultValueSql("(newid())");

				b.Property<Guid?>("GalleryId")
					.HasColumnType("uniqueidentifier")
					.HasColumnName("GalleryID");

				b.Property<string>("GalleryImageName")
					.HasMaxLength(512)
					.IsUnicode(false)
					.HasColumnName("GalleryImage")
					.HasColumnType("varchar(512)");

				b.Property<int?>("ImageOrder")
					.HasColumnType("int");

				b.HasKey("GalleryImageId")
					.HasName("tblGalleryImage_PK");

				b.HasIndex("GalleryId");

				b.ToTable("tblGalleryImage", (string)null);
			});

			modelBuilder.Entity("CarrotCake.CMS.Plugins.PhotoGallery.Data.GalleryImageMetaData", b => {
				b.Property<Guid>("GalleryImageMetaId")
					.ValueGeneratedOnAdd()
					.HasColumnType("uniqueidentifier")
					.HasColumnName("GalleryImageMetaID")
					.HasDefaultValueSql("(newid())");

				b.Property<string>("GalleryImageName")
					.HasMaxLength(512)
					.IsUnicode(false)
					.HasColumnType("varchar(512)");

				b.Property<string>("ImageMetaData")
					.IsUnicode(false)
					.HasColumnType("varchar(max)");

				b.Property<string>("ImageTitle")
					.HasMaxLength(256)
					.IsUnicode(false)
					.HasColumnType("varchar(256)");

				b.Property<Guid?>("SiteId")
					.HasColumnType("uniqueidentifier")
					.HasColumnName("SiteID");

				b.HasKey("GalleryImageMetaId")
					.HasName("tblGalleryImageMeta_PK");

				b.ToTable("tblGalleryImageMeta", (string)null);
			});

			modelBuilder.Entity("CarrotCake.CMS.Plugins.PhotoGallery.Data.GalleryImage", b => {
				b.HasOne("CarrotCake.CMS.Plugins.PhotoGallery.Data.Gallery", "Gallery")
					.WithMany("GalleryImages")
					.HasForeignKey("GalleryId")
					.HasConstraintName("tblGallery_tblGalleryImage_FK");

				b.Navigation("Gallery");
			});

			modelBuilder.Entity("CarrotCake.CMS.Plugins.PhotoGallery.Data.Gallery", b => {
				b.Navigation("GalleryImages");
			});
#pragma warning restore 612, 618
		}
	}
}
